#!/usr/bin/env python3
"""
Unit Tests for CourtListener MCP CitationTools

Comprehensive testing of verify_citations functionality including:
- Success scenarios with various parameters
- Error handling (401, 403, 404, 429, 500, timeout, network)
- Parameter validation and edge cases
- Performance requirements
- Data formatting validation

Generated by: tests/scripts/generate_unit_tests.py
"""

import pytest
import httpx
import time
from unittest.mock import AsyncMock, patch, MagicMock
from mcp.server.fastmcp import FastMCP

from tools.citation_tools import register_citation_tools


class TestCitationTools:
    """Unit tests for verify_citations - Verify and lookup legal citations"""
    
    @pytest.fixture
    async def mcp_server(self):
        """Create MCP server with citation_tools registered."""
        mcp = FastMCP(name="test")
        register_citation_tools(mcp)
        return mcp
    
    @pytest.fixture
    def mock_api_response(self):
        """Standard mock API response."""
        return {
            "count": 1,
            "results": [{
                "id": 12345,
                "date_created": "2020-01-15T10:30:00Z",
                "date_modified": "2020-01-15T10:30:00Z"
            }]
        }

    @pytest.mark.unit
    async def test_verify_citations_success(self, mcp_server, mock_api_response):
        """Test successful verify_citations execution."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = mock_api_response
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('verify_citations').call(
                
            )
            
            # Verify successful execution
            assert isinstance(result, str)
            assert len(result) > 0
            assert mock_get.called

    @pytest.mark.unit
    async def test_verify_citations_not_found(self, mcp_server):
        """Test verify_citations with no results found."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "No" in result or "not found" in result.lower()
    
    @pytest.mark.unit
    async def test_verify_citations_auth_error(self, mcp_server):
        """Test verify_citations authentication error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 401
            mock_get.return_value.json.return_value = {
                "detail": "Authentication credentials were not provided."
            }
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "authentication" in result.lower() or "unauthorized" in result.lower()
    
    @pytest.mark.unit
    async def test_verify_citations_forbidden_error(self, mcp_server):
        """Test verify_citations forbidden error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 403
            mock_get.return_value.json.return_value = {
                "detail": "You do not have permission to perform this action."
            }
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "permission" in result.lower() or "forbidden" in result.lower()
    
    @pytest.mark.unit
    async def test_verify_citations_rate_limit_error(self, mcp_server):
        """Test verify_citations rate limiting error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 429
            mock_get.return_value.json.return_value = {
                "detail": "Request was throttled. Expected available in 60 seconds."
            }
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "rate" in result.lower() or "throttled" in result.lower()
    
    @pytest.mark.unit
    async def test_verify_citations_server_error(self, mcp_server):
        """Test verify_citations server error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 500
            mock_get.return_value.text = "Internal Server Error"
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "error" in result.lower() or "server" in result.lower()
    
    @pytest.mark.unit
    async def test_verify_citations_network_timeout(self, mcp_server):
        """Test verify_citations network timeout handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.side_effect = httpx.TimeoutException("Request timeout")
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "timeout" in result.lower() or "network" in result.lower()
    
    @pytest.mark.unit
    async def test_verify_citations_connection_error(self, mcp_server):
        """Test verify_citations connection error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.side_effect = httpx.ConnectError("Connection failed")
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert "connection" in result.lower() or "network" in result.lower()

    @pytest.mark.unit
    async def test_verify_citations_parameter_validation(self, mcp_server):
        """Test verify_citations parameter validation."""
        # Test with valid parameters
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            # Should not raise exception with valid params
            assert isinstance(result, str)

    @pytest.mark.unit
    @pytest.mark.slow
    async def test_verify_citations_performance(self, mcp_server, mock_api_response):
        """Test verify_citations performance requirements."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = mock_api_response
            mock_get.return_value.status_code = 200
            
            start_time = time.time()
            result = await mcp_server.get_tool('verify_citations').call()
            end_time = time.time()
            
            # Should complete within reasonable time (5 seconds max)
            duration = end_time - start_time
            assert duration < 5.0, f"Tool took too long: {duration:.2f}s"
            assert isinstance(result, str)
            assert len(result) > 0
    
    @pytest.mark.unit
    async def test_verify_citations_large_result_handling(self, mcp_server):
        """Test verify_citations with large result sets."""
        # Mock large response
        large_response = {
            "count": 1000,
            "results": [{"id": i, "data": "x" * 100} for i in range(100)]
        }
        
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = large_response
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('verify_citations').call(limit=100)
            
            # Should handle large responses without issues
            assert isinstance(result, str)
            assert len(result) > 1000  # Should have substantial content

    @pytest.mark.unit
    async def test_verify_citations_empty_response(self, mcp_server):
        """Test verify_citations with empty API response."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert isinstance(result, str)
            # Should gracefully handle empty results
            assert len(result) > 0  # Should provide meaningful message
    
    @pytest.mark.unit
    async def test_verify_citations_malformed_response(self, mcp_server):
        """Test verify_citations with malformed API response."""
        with patch('httpx.AsyncClient.get') as mock_get:
            # Malformed JSON response
            mock_get.return_value.json.side_effect = ValueError("Invalid JSON")
            mock_get.return_value.status_code = 200
            mock_get.return_value.text = "Invalid JSON response"
            
            result = await mcp_server.get_tool('verify_citations').call()
            
            assert isinstance(result, str)
            assert "error" in result.lower() or "invalid" in result.lower()
