#!/usr/bin/env python3
"""
Unit Tests for CourtListener MCP SearchTools

Comprehensive testing of advanced_legal_search functionality including:
- Success scenarios with various parameters
- Error handling (401, 403, 404, 429, 500, timeout, network)
- Parameter validation and edge cases
- Performance requirements
- Data formatting validation

Generated by: tests/scripts/generate_unit_tests.py
"""

import pytest
import httpx
import time
from unittest.mock import AsyncMock, patch, MagicMock
from mcp.server.fastmcp import FastMCP

from tools.search_tools import register_search_tools


class TestSearchTools:
    """Unit tests for advanced_legal_search - Advanced legal search with complex parameters"""
    
    @pytest.fixture
    async def mcp_server(self):
        """Create MCP server with search_tools registered."""
        mcp = FastMCP(name="test")
        register_search_tools(mcp)
        return mcp
    
    @pytest.fixture
    def mock_api_response(self):
        """Standard mock API response."""
        return {
            "count": 1,
            "results": [{
                "id": 12345,
                "date_created": "2020-01-15T10:30:00Z",
                "date_modified": "2020-01-15T10:30:00Z"
            }]
        }

    @pytest.mark.unit
    async def test_advanced_legal_search_success(self, mcp_server, mock_api_response):
        """Test successful advanced_legal_search execution."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = mock_api_response
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('advanced_legal_search').call(
                query="contract law"
            )
            
            # Verify successful execution
            assert isinstance(result, str)
            assert len(result) > 0
            assert mock_get.called

    @pytest.mark.unit
    async def test_advanced_legal_search_not_found(self, mcp_server):
        """Test advanced_legal_search with no results found."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "No" in result or "not found" in result.lower()
    
    @pytest.mark.unit
    async def test_advanced_legal_search_auth_error(self, mcp_server):
        """Test advanced_legal_search authentication error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 401
            mock_get.return_value.json.return_value = {
                "detail": "Authentication credentials were not provided."
            }
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "authentication" in result.lower() or "unauthorized" in result.lower()
    
    @pytest.mark.unit
    async def test_advanced_legal_search_forbidden_error(self, mcp_server):
        """Test advanced_legal_search forbidden error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 403
            mock_get.return_value.json.return_value = {
                "detail": "You do not have permission to perform this action."
            }
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "permission" in result.lower() or "forbidden" in result.lower()
    
    @pytest.mark.unit
    async def test_advanced_legal_search_rate_limit_error(self, mcp_server):
        """Test advanced_legal_search rate limiting error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 429
            mock_get.return_value.json.return_value = {
                "detail": "Request was throttled. Expected available in 60 seconds."
            }
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "rate" in result.lower() or "throttled" in result.lower()
    
    @pytest.mark.unit
    async def test_advanced_legal_search_server_error(self, mcp_server):
        """Test advanced_legal_search server error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 500
            mock_get.return_value.text = "Internal Server Error"
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "error" in result.lower() or "server" in result.lower()
    
    @pytest.mark.unit
    async def test_advanced_legal_search_network_timeout(self, mcp_server):
        """Test advanced_legal_search network timeout handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.side_effect = httpx.TimeoutException("Request timeout")
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "timeout" in result.lower() or "network" in result.lower()
    
    @pytest.mark.unit
    async def test_advanced_legal_search_connection_error(self, mcp_server):
        """Test advanced_legal_search connection error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.side_effect = httpx.ConnectError("Connection failed")
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert "connection" in result.lower() or "network" in result.lower()

    @pytest.mark.unit
    async def test_advanced_legal_search_parameter_validation(self, mcp_server):
        """Test advanced_legal_search parameter validation."""
        # Test with valid parameters
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            # Should not raise exception with valid params
            assert isinstance(result, str)

    
    @pytest.mark.unit
    @pytest.mark.parametrize("limit_value", [-1, 0, 1001])
    async def test_advanced_legal_search_invalid_limit(self, mcp_server, limit_value):
        """Test advanced_legal_search with invalid limit values."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            # Some invalid limits might be handled gracefully
            result = await mcp_server.get_tool('advanced_legal_search').call(limit=limit_value)
            assert isinstance(result, str)

    @pytest.mark.unit
    @pytest.mark.slow
    async def test_advanced_legal_search_performance(self, mcp_server, mock_api_response):
        """Test advanced_legal_search performance requirements."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = mock_api_response
            mock_get.return_value.status_code = 200
            
            start_time = time.time()
            result = await mcp_server.get_tool('advanced_legal_search').call()
            end_time = time.time()
            
            # Should complete within reasonable time (5 seconds max)
            duration = end_time - start_time
            assert duration < 5.0, f"Tool took too long: {duration:.2f}s"
            assert isinstance(result, str)
            assert len(result) > 0
    
    @pytest.mark.unit
    async def test_advanced_legal_search_large_result_handling(self, mcp_server):
        """Test advanced_legal_search with large result sets."""
        # Mock large response
        large_response = {
            "count": 1000,
            "results": [{"id": i, "data": "x" * 100} for i in range(100)]
        }
        
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = large_response
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('advanced_legal_search').call(limit=100)
            
            # Should handle large responses without issues
            assert isinstance(result, str)
            assert len(result) > 1000  # Should have substantial content

    @pytest.mark.unit
    async def test_advanced_legal_search_empty_response(self, mcp_server):
        """Test advanced_legal_search with empty API response."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert isinstance(result, str)
            # Should gracefully handle empty results
            assert len(result) > 0  # Should provide meaningful message
    
    @pytest.mark.unit
    async def test_advanced_legal_search_malformed_response(self, mcp_server):
        """Test advanced_legal_search with malformed API response."""
        with patch('httpx.AsyncClient.get') as mock_get:
            # Malformed JSON response
            mock_get.return_value.json.side_effect = ValueError("Invalid JSON")
            mock_get.return_value.status_code = 200
            mock_get.return_value.text = "Invalid JSON response"
            
            result = await mcp_server.get_tool('advanced_legal_search').call()
            
            assert isinstance(result, str)
            assert "error" in result.lower() or "invalid" in result.lower()

    
    @pytest.mark.unit
    @pytest.mark.parametrize("special_query", [
        "", "   ", "a", "a" * 1000, "SELECT * FROM table", "<script>alert('xss')</script>"
    ])
    async def test_advanced_legal_search_special_queries(self, mcp_server, special_query):
        """Test advanced_legal_search with special query strings."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('advanced_legal_search').call(query=special_query)
            
            # Should handle special queries gracefully
            assert isinstance(result, str)
