#!/usr/bin/env python3
"""
Unit Tests for CourtListener MCP AbaRatingsTools

Comprehensive testing of get_aba_ratings functionality including:
- Success scenarios with various parameters
- Error handling (401, 403, 404, 429, 500, timeout, network)
- Parameter validation and edge cases
- Performance requirements
- Data formatting validation

Generated by: tests/scripts/generate_unit_tests.py
"""

import pytest
import httpx
import time
from unittest.mock import AsyncMock, patch, MagicMock
from mcp.server.fastmcp import FastMCP

from tools.aba_ratings_tools import register_aba_ratings_tools


class TestAbaRatingsTools:
    """Unit tests for get_aba_ratings - Retrieve ABA ratings for judges"""
    
    @pytest.fixture
    async def mcp_server(self):
        """Create MCP server with aba_ratings_tools registered."""
        mcp = FastMCP(name="test")
        register_aba_ratings_tools(mcp)
        return mcp
    
    @pytest.fixture
    def mock_api_response(self):
        """Standard mock API response."""
        return {
            "count": 1,
            "results": [{
                "id": 12345,
                "date_created": "2020-01-15T10:30:00Z",
                "date_modified": "2020-01-15T10:30:00Z"
            }]
        }

    @pytest.mark.unit
    async def test_get_aba_ratings_success(self, mcp_server, mock_api_response):
        """Test successful get_aba_ratings execution."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = mock_api_response
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('get_aba_ratings').call(
                person_id=8521
            )
            
            # Verify successful execution
            assert isinstance(result, str)
            assert len(result) > 0
            assert mock_get.called

    @pytest.mark.unit
    async def test_get_aba_ratings_not_found(self, mcp_server):
        """Test get_aba_ratings with no results found."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "No" in result or "not found" in result.lower()
    
    @pytest.mark.unit
    async def test_get_aba_ratings_auth_error(self, mcp_server):
        """Test get_aba_ratings authentication error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 401
            mock_get.return_value.json.return_value = {
                "detail": "Authentication credentials were not provided."
            }
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "authentication" in result.lower() or "unauthorized" in result.lower()
    
    @pytest.mark.unit
    async def test_get_aba_ratings_forbidden_error(self, mcp_server):
        """Test get_aba_ratings forbidden error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 403
            mock_get.return_value.json.return_value = {
                "detail": "You do not have permission to perform this action."
            }
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "permission" in result.lower() or "forbidden" in result.lower()
    
    @pytest.mark.unit
    async def test_get_aba_ratings_rate_limit_error(self, mcp_server):
        """Test get_aba_ratings rate limiting error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 429
            mock_get.return_value.json.return_value = {
                "detail": "Request was throttled. Expected available in 60 seconds."
            }
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "rate" in result.lower() or "throttled" in result.lower()
    
    @pytest.mark.unit
    async def test_get_aba_ratings_server_error(self, mcp_server):
        """Test get_aba_ratings server error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.status_code = 500
            mock_get.return_value.text = "Internal Server Error"
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "error" in result.lower() or "server" in result.lower()
    
    @pytest.mark.unit
    async def test_get_aba_ratings_network_timeout(self, mcp_server):
        """Test get_aba_ratings network timeout handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.side_effect = httpx.TimeoutException("Request timeout")
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "timeout" in result.lower() or "network" in result.lower()
    
    @pytest.mark.unit
    async def test_get_aba_ratings_connection_error(self, mcp_server):
        """Test get_aba_ratings connection error handling."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.side_effect = httpx.ConnectError("Connection failed")
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert "connection" in result.lower() or "network" in result.lower()

    @pytest.mark.unit
    async def test_get_aba_ratings_parameter_validation(self, mcp_server):
        """Test get_aba_ratings parameter validation."""
        # Test with valid parameters
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            # Should not raise exception with valid params
            assert isinstance(result, str)

    
    @pytest.mark.unit
    @pytest.mark.parametrize("limit_value", [-1, 0, 1001])
    async def test_get_aba_ratings_invalid_limit(self, mcp_server, limit_value):
        """Test get_aba_ratings with invalid limit values."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            # Some invalid limits might be handled gracefully
            result = await mcp_server.get_tool('get_aba_ratings').call(limit=limit_value)
            assert isinstance(result, str)

    
    @pytest.mark.unit
    async def test_get_aba_ratings_invalid_id_types(self, mcp_server):
        """Test get_aba_ratings with invalid ID types."""
        with patch('httpx.AsyncClient.get') as mock_get:
            # Test should handle invalid IDs gracefully
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            # Test with string instead of int for ID fields
            result = await mcp_server.get_tool('get_aba_ratings').call()
            assert isinstance(result, str)

    @pytest.mark.unit
    @pytest.mark.slow
    async def test_get_aba_ratings_performance(self, mcp_server, mock_api_response):
        """Test get_aba_ratings performance requirements."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = mock_api_response
            mock_get.return_value.status_code = 200
            
            start_time = time.time()
            result = await mcp_server.get_tool('get_aba_ratings').call()
            end_time = time.time()
            
            # Should complete within reasonable time (5 seconds max)
            duration = end_time - start_time
            assert duration < 5.0, f"Tool took too long: {duration:.2f}s"
            assert isinstance(result, str)
            assert len(result) > 0
    
    @pytest.mark.unit
    async def test_get_aba_ratings_large_result_handling(self, mcp_server):
        """Test get_aba_ratings with large result sets."""
        # Mock large response
        large_response = {
            "count": 1000,
            "results": [{"id": i, "data": "x" * 100} for i in range(100)]
        }
        
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = large_response
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('get_aba_ratings').call(limit=100)
            
            # Should handle large responses without issues
            assert isinstance(result, str)
            assert len(result) > 1000  # Should have substantial content

    @pytest.mark.unit
    async def test_get_aba_ratings_empty_response(self, mcp_server):
        """Test get_aba_ratings with empty API response."""
        with patch('httpx.AsyncClient.get') as mock_get:
            mock_get.return_value.json.return_value = {"count": 0, "results": []}
            mock_get.return_value.status_code = 200
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert isinstance(result, str)
            # Should gracefully handle empty results
            assert len(result) > 0  # Should provide meaningful message
    
    @pytest.mark.unit
    async def test_get_aba_ratings_malformed_response(self, mcp_server):
        """Test get_aba_ratings with malformed API response."""
        with patch('httpx.AsyncClient.get') as mock_get:
            # Malformed JSON response
            mock_get.return_value.json.side_effect = ValueError("Invalid JSON")
            mock_get.return_value.status_code = 200
            mock_get.return_value.text = "Invalid JSON response"
            
            result = await mcp_server.get_tool('get_aba_ratings').call()
            
            assert isinstance(result, str)
            assert "error" in result.lower() or "invalid" in result.lower()
